version: '3.8'

services:
  water-app:
    image: water-dashboard:${TAG:-latest}
    container_name: water-app
    restart: always
    ports:
      - "3000:4000"
    environment:
      - NODE_ENV=production
      - NITRO_PRESET=node

    networks:
      - water-network

networks:
  water-network:
    driver: bridge
