services:
  water-app:
    image: water-dashboard:${TAG:-latest}
    container_name: water-app
    restart: always
    ports:
      - "3000:4000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - NITRO_PRESET=node
      - TZ=Asia/Shanghai

    networks:
      - water-network

networks:
  water-network:
    driver: bridge
