export default [

  {
    id: 1,
    path: '/',
    name: 'basic',
    label: '基础信息',
    component: 'basic',
    parentPath: null,
    meta: {
      title: '基础信息',
      icon: '',
      isExt: false,
      extOpenMode: 1,
      type: 0,
      orderNo: 1,
      show: 1,
      activeMenu: null,
      status: 1,
      keepAlive: 0,
    },
  },

  // {
  //   id: 1,
  //   path: '/',
  //   name: 'basic',
  //   label: '基础信息',
  //   component: 'basic',
  //   parentPath: null,
  //   meta: {
  //     title: '基础信息',
  //     icon: '',
  //     isExt: false,
  //     extOpenMode: 1,
  //     type: 0,
  //     orderNo: 1,
  //     show: 1,
  //     activeMenu: null,
  //     status: 1,
  //     keepAlive: 0,
  //   },
  //   children: [
  //     {
  //       id: 2,
  //       path: '/basic/overview',
  //       name: 'basicOverview',
  //       label: '概览',
  //       component: 'basic/overview',
  //       parentPath: '/basic',
  //       meta: {
  //         title: '概览',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 1,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //     {
  //       id: 3,
  //       path: '/basic/detail',
  //       name: 'basicDetail',
  //       label: '详情',
  //       component: 'basic/detail',
  //       parentPath: '/basic',
  //       meta: {
  //         title: '详情',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 2,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //   ],
  // },
  // {
  //   id: 4,
  //   path: '/stat',
  //   name: 'stat',
  //   label: '统计报表',
  //   component: 'stat',
  //   parentPath: null,
  //   meta: {
  //     title: '统计报表',
  //     icon: '',
  //     isExt: false,
  //     extOpenMode: 1,
  //     type: 0,
  //     orderNo: 2,
  //     show: 1,
  //     activeMenu: null,
  //     status: 1,
  //     keepAlive: 0,
  //   },
  //   children: [
  //     {
  //       id: 5,
  //       path: '/stat/dashboard',
  //       name: 'statDashboard',
  //       label: '统计看板',
  //       component: 'stat/dashboard',
  //       parentPath: '/stat',
  //       meta: {
  //         title: '统计看板',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 1,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //     {
  //       id: 6,
  //       path: '/stat/MeterReading',
  //       name: 'statMeterReading',
  //       label: '远程抄表',
  //       component: 'stat/MeterReading',
  //       parentPath: '/stat',
  //       meta: {
  //         title: '远程抄表',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 2,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //     {
  //       id: 7,
  //       path: '/stat/EnergyRank',
  //       name: 'statEnergyRank',
  //       label: '用能排名',
  //       component: 'stat/EnergyRank',
  //       parentPath: '/stat',
  //       meta: {
  //         title: '用能排名',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 3,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //     {
  //       id: 8,
  //       path: '/stat/Query',
  //       name: 'statQuery',
  //       label: '统计查询',
  //       component: 'stat/Query',
  //       parentPath: '/stat',
  //       meta: {
  //         title: '统计查询',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 4,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //   ],
  // },
  // {
  //   id: 9,
  //   path: '/anal',
  //   name: 'anal',
  //   label: '用水分析',
  //   component: 'anal',
  //   parentPath: null,
  //   meta: {
  //     title: '用水分析',
  //     icon: '',
  //     isExt: false,
  //     extOpenMode: 1,
  //     type: 0,
  //     orderNo: 3,
  //     show: 1,
  //     activeMenu: null,
  //     status: 1,
  //     keepAlive: 0,
  //   },
  //   children: [
  //     {
  //       id: 10,
  //       path: '/anal/dynamic',
  //       name: 'analDynamic',
  //       label: '动态分析',
  //       component: 'anal/dynamic',
  //       parentPath: '/anal',
  //       meta: {
  //         title: '动态分析',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 1,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //     {
  //       id: 11,
  //       path: '/anal/supply',
  //       name: 'analSupply',
  //       label: '供水分析',
  //       component: 'anal/supply',
  //       parentPath: '/anal',
  //       meta: {
  //         title: '供水分析',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 2,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //     {
  //       id: 12,
  //       path: '/anal/leakage',
  //       name: 'analLeakage',
  //       label: '漏损分析',
  //       component: 'anal/leakage',
  //       parentPath: '/anal',
  //       meta: {
  //         title: '漏损分析',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 3,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //   ],
  // },
  // {
  //   id: 13,
  //   path: '/alarm',
  //   name: 'alarm',
  //   label: '报警管理',
  //   component: 'alarm',
  //   parentPath: null,
  //   meta: {
  //     title: '报警管理',
  //     icon: '',
  //     isExt: false,
  //     extOpenMode: 1,
  //     type: 0,
  //     orderNo: 4,
  //     show: 1,
  //     activeMenu: null,
  //     status: 1,
  //     keepAlive: 0,
  //   },
  //   children: [
  //     {
  //       id: 14,
  //       path: '/alarm/monitor',
  //       name: 'alarmMonitor',
  //       label: '报警监控',
  //       component: 'alarm/monitor',
  //       parentPath: '/alarm',
  //       meta: {
  //         title: '报警监控',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 1,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //   ],
  // },
  // {
  //   id: 15,
  //   path: '/quota',
  //   name: 'quota',
  //   label: '定额管理',
  //   component: 'quota',
  //   parentPath: null,
  //   meta: {
  //     title: '定额管理',
  //     icon: '',
  //     isExt: false,
  //     extOpenMode: 1,
  //     type: 0,
  //     orderNo: 5,
  //     show: 1,
  //     activeMenu: null,
  //     status: 1,
  //     keepAlive: 0,
  //   },
  //   children: [
  //     {
  //       id: 16,
  //       path: '/quota/dashboard',
  //       name: 'quotaDashboard',
  //       label: '定额看板',
  //       component: 'quota/dashboard',
  //       parentPath: '/quota',
  //       meta: {
  //         title: '定额看板',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 1,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //     {
  //       id: 17,
  //       path: '/quota/settings',
  //       name: 'quotaSettings',
  //       label: '定额配置',
  //       component: 'quota/settings',
  //       parentPath: '/quota',
  //       meta: {
  //         title: '定额配置',
  //         icon: '',
  //         isExt: false,
  //         extOpenMode: 1,
  //         type: 1,
  //         orderNo: 2,
  //         show: 1,
  //         activeMenu: null,
  //         status: 1,
  //         keepAlive: 0,
  //       },
  //     },
  //   ],
  // },
]
