# name: CI

# on:
#   push:
#     branches:
#       - main
#       # ：当推送到 main 分支时触发工作流。

#   pull_request:
#     branches:
#       - main
#       # 当创建针对 main 分支的拉取请求时触发工作流。

# jobs:
#   lint:
#     runs-on: ubuntu-latest   #在最新的 Ubuntu 环境中运行。
#     steps:
#       - uses: actions/checkout@v3  # 检查仓库
#       - uses: pnpm/action-setup@v2  # 安装 pnpm
#       - uses: actions/setup-node@v3 # 安装 Node.js
#         with:
#           node-version: lts/*  # 使用 LTS 版本的 Node.js
#           cache: pnpm  # 使用 pnpm 作为缓存

#       - name: Install  # 安装依赖
#         run: pnpm install  # 使用 pnpm 安装依赖

#       - name: Lint   # 检查代码
#         run: pnpm run lint  # 使用 pnpm 检查代码

#   typecheck:
#     runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行
#     steps:
#       - uses: actions/checkout@v3 # 检查仓库
#       - uses: pnpm/action-setup@v2  # 安装 pnpm
#       - uses: actions/setup-node@v3  # 安装 Node.js
#         with:
#           node-version: lts/*
#           cache: pnpm

#       - name: Install
#         run: pnpm install

#       - name: Typecheck      # 检查类型
#         run: pnpm run typecheck  # 使用 pnpm 检查类型
